### ISSUE TITLE
My email doesn't work

### ISSUE THREAD

**Issue by Monacr** [Monacr/FitSocial#8] opened 2023-02-22 02:42 UTC
I tried to create an email with my school email but it wouldnt let me

I can reproduce by following these steps:
Enter school email with @uw.edu on signup page

Expected: Account is created
Actual: Email is denied

**Comment by Lawqup** [comment] 2023-02-28 02:03
Duplicate of #9

**Closed as completed by Lawqup** 2023-02-28 02:03 UTC
